// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProfOaksKantoPokedex.DbContexts;

#nullable disable

namespace ProfOaksKantoPokedex.Migrations
{
    [DbContext(typeof(ProfOaksKantoPokedexContext))]
    [Migration("20221206144332_moveDeleteForDemo")]
    partial class moveDeleteForDemo
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.0");

            modelBuilder.Entity("ProfOaksKantoPokedex.Entities.MoveLearnt", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Accuracy")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("LevelLearnt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MoveCategory")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("PokemonId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Power")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TypeOfMove")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PokemonId");

                    b.ToTable("MovesLearnt");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Accuracy = 100,
                            Description = "Reduces the foe’s ATTACK.",
                            LevelLearnt = 1,
                            MoveCategory = "Status",
                            Name = "Growl",
                            PokemonId = 1,
                            Power = 0,
                            TypeOfMove = "Normal"
                        },
                        new
                        {
                            Id = 2,
                            Accuracy = 95,
                            Description = "A full-body charge attack.",
                            LevelLearnt = 1,
                            MoveCategory = "Physical",
                            Name = "Tackle",
                            PokemonId = 1,
                            Power = 35,
                            TypeOfMove = "Normal"
                        },
                        new
                        {
                            Id = 3,
                            Accuracy = 90,
                            Description = "Steals HP from the foe on every turn.",
                            LevelLearnt = 1,
                            MoveCategory = "Status",
                            Name = "Leech Seed",
                            PokemonId = 1,
                            Power = 0,
                            TypeOfMove = "Grass"
                        },
                        new
                        {
                            Id = 4,
                            Accuracy = 100,
                            Description = "Reduces the foe’s ATTACK.",
                            LevelLearnt = 1,
                            MoveCategory = "Status",
                            Name = "Growl",
                            PokemonId = 2,
                            Power = 0,
                            TypeOfMove = "Normal"
                        },
                        new
                        {
                            Id = 5,
                            Accuracy = 90,
                            Description = "Steals HP from the foe on every turn.",
                            LevelLearnt = 1,
                            MoveCategory = "Status",
                            Name = "Leech Seed",
                            PokemonId = 2,
                            Power = 0,
                            TypeOfMove = "Grass"
                        },
                        new
                        {
                            Id = 6,
                            Accuracy = 95,
                            Description = "A full-body charge attack.",
                            LevelLearnt = 1,
                            MoveCategory = "Physical",
                            Name = "Tackle",
                            PokemonId = 2,
                            Power = 35,
                            TypeOfMove = "Normal"
                        },
                        new
                        {
                            Id = 7,
                            Accuracy = 100,
                            Description = "Reduces the foe’s ATTACK.",
                            LevelLearnt = 1,
                            MoveCategory = "Status",
                            Name = "Growl",
                            PokemonId = 3,
                            Power = 0,
                            TypeOfMove = "Normal"
                        },
                        new
                        {
                            Id = 8,
                            Accuracy = 90,
                            Description = "Steals HP from the foe on every turn.",
                            LevelLearnt = 1,
                            MoveCategory = "Status",
                            Name = "Leech Seed",
                            PokemonId = 3,
                            Power = 0,
                            TypeOfMove = "Grass"
                        },
                        new
                        {
                            Id = 9,
                            Accuracy = 95,
                            Description = "A full-body charge attack.",
                            LevelLearnt = 1,
                            MoveCategory = "Physical",
                            Name = "Tackle",
                            PokemonId = 3,
                            Power = 35,
                            TypeOfMove = "Normal"
                        });
                });

            modelBuilder.Entity("ProfOaksKantoPokedex.Entities.Pokemon", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Ability")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("BaseStatTotal")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Pokemon");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Ability = "Overgrow",
                            BaseStatTotal = 318,
                            Description = "There is a plant seed on its back right from the day this Pokémon is born. The seed slowly grows larger.",
                            Name = "Bulbasaur",
                            Type = "Grass, Posion"
                        },
                        new
                        {
                            Id = 2,
                            Ability = "Overgrow",
                            BaseStatTotal = 405,
                            Description = "When the bulb on its back grows large, it appears to lose the ability to stand on its hind legs.",
                            Name = "Ivysaur",
                            Type = "Grass, Posion"
                        },
                        new
                        {
                            Id = 3,
                            Ability = "Overgrow",
                            BaseStatTotal = 525,
                            Description = "Its plant blooms when it is absorbing solar energy. It stays on the move to seek sunlight.",
                            Name = "Venusaur",
                            Type = "Grass, Posion"
                        });
                });

            modelBuilder.Entity("ProfOaksKantoPokedex.Entities.MoveLearnt", b =>
                {
                    b.HasOne("ProfOaksKantoPokedex.Entities.Pokemon", "Pokemon")
                        .WithMany("MovesLearnt")
                        .HasForeignKey("PokemonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pokemon");
                });

            modelBuilder.Entity("ProfOaksKantoPokedex.Entities.Pokemon", b =>
                {
                    b.Navigation("MovesLearnt");
                });
#pragma warning restore 612, 618
        }
    }
}
