// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProfOaksKantoPokedex.DbContexts;

#nullable disable

namespace ProfOaksKantoPokedex.Migrations
{
    [DbContext(typeof(ProfOaksKantoPokedexContext))]
    [Migration("20221122140206_ProfOaksKantoPokedexDbAddDescription")]
    partial class ProfOaksKantoPokedexDbAddDescription
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.0");

            modelBuilder.Entity("ProfOaksKantoPokedex.Entities.MoveLearnt", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Accuracy")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("LevelLearnt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MoveCategory")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("PokemonId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Power")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TypeOfMove")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PokemonId");

                    b.ToTable("MovesLearnt");
                });

            modelBuilder.Entity("ProfOaksKantoPokedex.Entities.Pokemon", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Ability")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("BaseStatTotal")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Pokemon");
                });

            modelBuilder.Entity("ProfOaksKantoPokedex.Entities.MoveLearnt", b =>
                {
                    b.HasOne("ProfOaksKantoPokedex.Entities.Pokemon", "Pokemon")
                        .WithMany("MovesLearnt")
                        .HasForeignKey("PokemonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pokemon");
                });

            modelBuilder.Entity("ProfOaksKantoPokedex.Entities.Pokemon", b =>
                {
                    b.Navigation("MovesLearnt");
                });
#pragma warning restore 612, 618
        }
    }
}
